### ISSUE TITLE
`dataset_processing.py` file

### ISSUE THREAD

**Issue by yukkiXie** [ispamm/GESCO#12]
Dear authors,
I hope this message finds you well. I have been using your source code 'image_train.py' to train a model on my own, but I am encountering an issue where the model file I trained does not align with the number of classes, making it impossible to perform testing on the provided test files 'image_sample.py'.

In light of this, I wanted to inquire if it would be possible for you to provide a `dataset_processing.py` file specifically designed for handling images and labels processing for the Cityscapes and COCO datasets. By having this file, I can ensure consistency in the dataset during both the training and testing phases, enabling me to accurately evaluate the model's performance.

Thank you very much for your time and assistance. I greatly appreciate any advice or guidance you can provide.

**Comment by eleGAN23** [comment]
Dear Sir,
the datasets preprocessing has been performed according to the SPADE paper. It can be found on their repository: https://github.com/NVlabs/SPADE.

Best regards,
Eleonora
